### ISSUE TITLE
[Bug] Active Section's NavItem Not Highlighted in Navigation Bar

### ISSUE THREAD

**Issue by gawandeabhishek** [creativecommons/vocabulary-theme#67]
## Description
When navigating through different sections of the website using the navigation bar, the active section's corresponding NavItem is not highlighted. This creates confusion for users as they are unable to easily identify their current location within the website's structure.

## Reproduction
1. Navigate to the website -> https://creativecommons.org/
2. Use the navigation bar to switch between different sections.
3. Note that the NavItem for the active section is not highlighted with the same text color as when hovering over it.

## Expectation
The NavItem for the active section should be highlighted with the same text color as when hovering over it, providing clear visual feedback to the user about their current location within the website.

## Screenshots
<img width="960" alt="image" src="https://github.com/creativecommons/chooser/assets/136836702/fff3be88-eb44-492a-984b-444c02063625">

## Environment

 - Device: laptop
 - OS: Windows
 - Browser: Chrome
 - Other info: Node.js version (v13.14.0)
 - Other info:  set the environment variable `VUE_APP_CC_OUTPUT=embedded` on your server before starting for resolving this bug

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Hi and thank you for this contribution! 

This is outside the scope of features we'd hope to add to the navigation, and would possibly create confusion since there are several pages that don't appear under those section, nor do they appear in the primary nav and therefore couldn't be highlighted when visited which would create more confusion in the UX.

**Comment by gawandeabhishek** [comment]
Hi @possumbilities, I hope you're doing well. I wanted to inquire about whether I should still consider applying for GSoC with Creative Commons. Unfortunately, I began learning web development about 7-8 months ago, and I stumbled upon this organization that I really wanted to contribute to this month. However, due to ongoing exams, I couldn't start contributing to Creative Commons until late. I understand what needs to be done to enhance the website's efficiency, but I'm struggling to locate the specific repository where the code resides. I've explored several repositories, but haven't found the relevant code. Could you please provide guidance? I'm committed to making 2-3 meaningful contributions to Creative Commons, and then I plan to submit a well-thought-out GSoC proposal. Thank you for your assistance.
